# Generated by Django 6.0.2 on 2026-06-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_portfolio_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='budget',
            field=models.CharField(blank=True, max_length=100, verbose_name='بودجه تقریبی'),
        ),
        migrations.AddField(
            model_name='order',
            name='deadline',
            field=models.CharField(blank=True, max_length=100, verbose_name='زمان تحویل'),
        ),
    ]
