# Generated by Django 6.0.2 on 2026-06-23 01:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_budget_order_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField()),
                ('stars', models.IntegerField(default=5)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='deadline',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='budget',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('review', 'در حال بررسی'), ('working', 'در حال انجام'), ('completed', 'تحویل شده')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='base_price',
            field=models.PositiveIntegerField(verbose_name='قیمت پایه'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
